version: '3.8'

services:
  redis-db:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - spring-todo-app-network
    depends_on:
      - postgres-db       

  app:  
    build: 
      context: .
    container_name: spring-app
    depends_on:
      - redis-db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default   
      SPRING_DATASOURCE_URL: $DOCKER_DB_URL
      SPRING_DATASOURCE_USERNAME: $DB_USERNAME
      SPRING_DATASOURCE_PASSWORD: $DB_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: update 
      ACCESS_TOKEN_SECRET_KEY: $ACCESS_TOKEN_SECRET_KEY
      REFRESH_TOKEN_SECRET_KEY: $REFRESH_TOKEN_SECRET_KEY
      DOCKER_REDIS_HOST : $DOCKER_REDIS_HOST
      REDIS_PORT : $REDIS_PORT
      GOOGLE_CLIENT_ID : $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET : $GOOGLE_CLIENT_SECRET
    networks:
      - spring-todo-app-network

  postgres-db:
    image: postgres:latest
    restart: always
    container_name: spring-postgres-db    
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD  
      POSTGRES_DB: $DB_NAME
    ports:
      - "5430:5432"  
    volumes:
      - ./../spring-postgres-data:/var/lib/postgresql/data
    networks:
      - spring-todo-app-network   

networks:
  spring-todo-app-network:
    driver: bridge